/* GENERATED by scripts/build.mjs - do not edit.
   Source of truth is /forms/*.json. */

export const SEED_FORMS = [
  {
    "id": "gc-1",
    "code": "GC-1",
    "title": "Grievance & Casus Belli Intake Form",
    "mode": "generated",
    "bankId": "cic-core",
    "order": 10,
    "chip": "CONTINUOUS",
    "indexBlurb": "Mandatory before any declaration of hostilities against the Concern will be acknowledged, reviewed, tabled, or otherwise considered to exist. Generates its own continuation sheets.",
    "org": "CONSOLIDATED INDUSTRIAL CONCERN",
    "department": "Office of Interdepartmental Grievance Review",
    "enforceRequired": false
  },
  {
    "id": "gc-2",
    "code": "GC-2",
    "title": "Proof of Standing",
    "subtitle": "To be filed before, not after, the grievance it supports.",
    "mode": "static",
    "order": 20,
    "chip": "PREREQUISITE",
    "indexBlurb": "Establishes that the declaring party exists, is named, and is entitled to be aggrieved. Required as an attachment to Form GC-1, which cannot be filed without it.",
    "org": "CONSOLIDATED INDUSTRIAL CONCERN",
    "department": "Standing Committee on Standing",
    "revision": "REV. 12",
    "meta": [
      "ATTACHMENT TO GC-1",
      "DO NOT DETACH"
    ],
    "enforceRequired": true,
    "instructions": "**Before you begin:** standing is not the same as grievance. A party may be gravely wronged and still lack standing to say so. This sheet determines only the latter. It does not determine the former, and nothing on it will be read by anyone who does.",
    "sections": [
      {
        "title": "Entity Identification",
        "fields": [
          {
            "name": "entity_name",
            "type": "text",
            "label": "Full legal name of the entity",
            "placeholder": "As registered, not as transmitted",
            "required": true,
            "width": "half"
          },
          {
            "name": "entity_short",
            "type": "text",
            "label": "Name used in correspondence",
            "placeholder": "If different",
            "width": "half"
          },
          {
            "name": "name_is_word",
            "type": "radio",
            "label": "Is the entity's name a common word meaning “not known”?",
            "options": [
              "No",
              "Yes",
              "Yes, and this is intentional",
              "Yes, and the irony has been noted internally"
            ],
            "required": true
          },
          {
            "name": "spelling_variants",
            "type": "text",
            "label": "All spellings of the entity name appearing in your own transmissions",
            "placeholder": "Include any containing a transposed consonant",
            "help": "Where two spellings appear, the Office registers two entities and requires this form from each."
          }
        ],
        "note": "An entity that cannot be distinguished from the absence of an entity is filed under Schedule D."
      },
      {
        "title": "Capacity to Be Aggrieved",
        "fields": [
          {
            "name": "existed_before",
            "type": "checkbox",
            "label": "The entity existed prior to the events complained of.",
            "required": true
          },
          {
            "name": "exists_now",
            "type": "checkbox",
            "label": "The entity exists as at the date of this filing."
          },
          {
            "name": "will_exist",
            "type": "checkbox",
            "label": "The entity expects to exist on the date this filing is reviewed.",
            "help": "Reviews are scheduled 47 – ∞ business days out. Answer conservatively."
          },
          {
            "name": "basis",
            "type": "select",
            "label": "Basis on which standing is asserted",
            "options": [
              "Ownership of the asset concerned",
              "Custody of the asset concerned",
              "Proximity to the asset concerned",
              "Strength of feeling about the asset concerned",
              "None — asserting standing on general principle"
            ],
            "required": true
          }
        ]
      },
      {
        "title": "Prior Conduct Disclosure",
        "fields": [
          {
            "name": "prior_declarations",
            "type": "number",
            "label": "Declarations of war previously issued by the entity",
            "min": 0,
            "width": "half"
          },
          {
            "name": "prior_retracted",
            "type": "number",
            "label": "Of those, how many were retracted",
            "min": 0,
            "width": "half"
          },
          {
            "name": "prior_unretracted",
            "type": "number",
            "label": "Of those retractions, how many were themselves retracted",
            "min": 0,
            "width": "half"
          },
          {
            "name": "net_state",
            "type": "text",
            "label": "Resulting net state of belligerence",
            "placeholder": "Show your working if the figure is negative",
            "width": "half"
          },
          {
            "name": "own_tag_conduct",
            "type": "textarea",
            "label": "Describe any occasion on which a member of your entity acted under your tag without instruction, and what you did about it afterwards.",
            "rows": 4,
            "help": "Answers here are compared against the position taken in your grievance. They are not compared favourably."
          }
        ]
      },
      {
        "title": "Certification",
        "seal": true,
        "sealLabel": "GC-2",
        "fields": [
          {
            "name": "signature",
            "type": "signature",
            "label": "Signature of the party asserting standing",
            "placeholder": "Sign here",
            "required": true
          },
          {
            "name": "sig_date",
            "type": "date",
            "label": "Date"
          },
          {
            "name": "notary",
            "type": "signature",
            "label": "Notary public signature",
            "placeholder": "Currently on sabbatical — see Form GC-9",
            "disabled": true
          }
        ]
      }
    ],
    "officeUseTitle": "Registry Endorsement",
    "officeUse": [
      {
        "label": "STANDING",
        "value": "Not yet assessed"
      },
      {
        "label": "ROUTED TO",
        "value": "Cabinet 7, Drawer C"
      },
      {
        "label": "ESTIMATED REVIEW",
        "value": "47 – ∞ business days"
      }
    ],
    "finePrint": "Establishing standing does not advance any grievance, entitle the declaring party to a response, or oblige the Concern to agree that the entity exists. It permits the filing of Form GC-1, which is itself continuous.",
    "submitLabel": "LODGE PROOF OF STANDING",
    "receipt": {
      "stamp": "ACCEPTED",
      "message": "Standing provisionally noted for **{{code}}**, reference **{{ref}}**, queue position **{{queue}}**. You may now begin the grievance itself, which is a separate and longer matter.",
      "footnotes": [
        "Note: Provisional standing lapses if not exercised, and cannot be exercised until reviewed.",
        "Note: Your entity has been registered under each spelling supplied. Each will require its own Form GC-1.",
        "Note: The Standing Committee on Standing is currently assessing whether it has standing to assess standing."
      ],
      "next": {
        "mode": "form",
        "formId": "gc-1",
        "label": "Proceed to Form GC-1 →"
      }
    }
  }
];

export const SEED_BANKS = [
  {
    "kind": "bank",
    "id": "cic-core",
    "name": "CIC Core Grievance Bank",
    "description": "Question pool for the Office of Interdepartmental Grievance Review. Slots expand combinatorially, so the supply of paperwork is not meaningfully finite.",
    "page": {
      "minSections": 3,
      "maxSections": 4,
      "minQuestionsPerSection": 2,
      "maxQuestionsPerSection": 4,
      "maxLongAnswers": 1
    },
    "slots": {
      "form": [
        "GC-2",
        "GC-3",
        "GC-3a",
        "GC-4",
        "GC-5",
        "GC-7",
        "GC-9",
        "GC-11",
        "GC-12",
        "GC-14(b)",
        "GC-22",
        "GC-31(c)",
        "GC-40",
        "GC-44(b)(ii)",
        "Schedule Q",
        "Schedule Q-Annex",
        "Annex 6",
        "Form P-0",
        "Form ZZ"
      ],
      "ledger": [
        "Ledger 7",
        "Ledger 7, Column C",
        "Ledger 7, Column C (reverse)",
        "the Grey Ledger",
        "the Unreconciled Ledger",
        "Appendix N",
        "the Pending Drawer",
        "Cabinet 7, Drawer C",
        "the Overflow Cabinet"
      ],
      "officer": [
        "the Deputy Adjunct Registrar",
        "the Under-Clerk of Grievances",
        "the Second Assistant Notary",
        "the Acting Interim Archivist",
        "the Clerk of Unreconciled Matters",
        "the Registrar of Hostile Correspondence",
        "the Custodian of Cabinet 7",
        "the Deputy Comptroller of Feelings",
        "the Adjudicator of Vibes",
        "the Officer of the Day (unfilled)"
      ],
      "dept": [
        "Interdepartmental Grievance Review",
        "Hostile Correspondence Intake",
        "the Office of Retroactive Peace",
        "Asset Valuation & Mourning",
        "the Bureau of Declared Intentions",
        "Non-Combat Operations",
        "the Directorate of Polite Refusal",
        "Accounts Receivable (Grievances)",
        "the Standing Committee on Standing"
      ],
      "unit": [
        "business days",
        "fiscal quarters",
        "billing cycles",
        "standard weeks",
        "notarised fortnights",
        "audit periods",
        "working months",
        "review intervals of indeterminate length"
      ],
      "asset": [
        "shipyard",
        "refinery",
        "ore barge",
        "logistics spur",
        "forward depot",
        "smelting platform",
        "survey drone",
        "cargo hauler",
        "orbital warehouse",
        "fuel tender",
        "mining claim",
        "relay mast"
      ],
      "sum": [
        "4,000 credits",
        "17,500 credits",
        "1 credit",
        "an undisclosed sum",
        "a sum to be determined by {{officer}}",
        "220,000 credits",
        "the contents of a small tin",
        "no less than 6,000 credits"
      ],
      "abstract": [
        "standing",
        "intent",
        "aggrievement",
        "materiality",
        "proximate cause",
        "moral position",
        "commercial injury",
        "reputational exposure",
        "narrative coherence"
      ],
      "verb": [
        "burned",
        "scrapped",
        "erased",
        "neutralised",
        "removed",
        "cleaned up",
        "marked for deletion",
        "reduced to constituent components"
      ],
      "adverb": [
        "formally",
        "provisionally",
        "retroactively",
        "conditionally",
        "without prejudice",
        "in triplicate",
        "under protest",
        "for accounting purposes only"
      ],
      "frequency": [
        "0xUNKNOWN",
        "0x0000",
        "an unlisted band",
        "the emergency channel (misused)",
        "a frequency the Office cannot confirm exists"
      ]
    },
    "titles": [
      "Grievance & Casus Belli Intake Form",
      "Supplementary Grievance Particulars",
      "Declaration of Hostile Intent — Continuation Sheet",
      "Casus Belli Substantiation Worksheet",
      "Proof of Standing to Declare",
      "Certificate of Grievance Severity",
      "Severity Pre-Assessment Worksheet",
      "Statement of Non-Duplicative Grievance",
      "Third-Party Conduct Attribution Claim",
      "Notice of Retraction",
      "Notice of Retraction of Retraction",
      "Request for Alternate Notarisation",
      "Coordinate Disclosure Attestation",
      "Schedule of Assets Alleged Destroyed",
      "Photographic Evidence Cover Sheet",
      "Transmission Authenticity Declaration",
      "Encryption Key Custody Record",
      "Orthographic Correction Request",
      "Declaring Party Name Reconciliation",
      "Belligerent Entity Registration",
      "Notice of Intent to Continue Intending",
      "War Aims Itemisation Schedule",
      "Contractor & Hired Belligerent Manifest",
      "Waiver of Further Warnings",
      "Acknowledgement of Non-Acknowledgement",
      "Grievance Chronology Reconstruction",
      "Tag Custody & Attribution Ledger",
      "Membership Readmission Objection",
      "Ideological Consistency Audit Request",
      "Statement of Hypocrisy Particulars",
      "Neutrality Challenge Submission",
      "Application to Dispute a Filing Fee",
      "Request for Expedited Review (Denied in Advance)",
      "Standing Grievance Renewal Notice",
      "Quarterly Hostility Reconciliation",
      "Amendment to a Form Not Yet Filed",
      "Notice of Correspondence Received",
      "Declaration Regarding Declarations",
      "Sector Erasure Feasibility Questionnaire",
      "Claim for Emotional Damage to a Corporation",
      "Statement of Intent to Escalate",
      "Escalation De-Escalation Worksheet",
      "Preliminary Findings Acknowledgement Sheet",
      "Terminal Grievance Summary (Non-Terminal)"
    ],
    "subtitles": [
      "“Omnis Questus, Nullus Sanguis” — All Profit, No Blood",
      "“Every Grievance a Line Item”",
      "To be completed in full. Completion is not a defence.",
      "This sheet supersedes nothing and is superseded by everything.",
      "Filed in perpetuity. Reviewed at leisure.",
      "The Concern does not fight. The Concern files.",
      "Retain your copy. The Office will retain theirs.",
      "Page 1 of an indeterminate number.",
      "Neutral by policy. Thorough by temperament.",
      "A continuation of a matter that has not yet begun."
    ],
    "departments": [
      "Office of Interdepartmental Grievance Review",
      "Bureau of Hostile Correspondence Intake",
      "Directorate of Polite Refusal",
      "Office of Retroactive Peace",
      "Standing Committee on Standing",
      "Non-Combat Operations — Paperwork Division",
      "Asset Valuation & Mourning",
      "Accounts Receivable (Grievances)",
      "Office of the Notary (Sabbatical)",
      "Sub-Office of Duplicate Filings",
      "Registry of Declared Intentions",
      "Department of Vibes Adjudication"
    ],
    "metaLines": [
      "SHEET RETAINED REGARDLESS",
      "DO NOT DETACH",
      "COPY 3 OF 3 — ILLEGIBLE",
      "SUPERSEDES NOTHING",
      "FILE UNDER PENDING",
      "NOT A RECEIPT",
      "ORIGINAL MISLAID",
      "CARBON ONLY",
      "ROUTING: {{ledger}}",
      "CLERK: {{officer}}"
    ],
    "instructions": [
      "**Before you begin:** this sheet must be completed in full before the matter it concerns can be considered to exist. Incomplete submissions are not rejected — they are filed alongside complete ones, in the same drawer, in no particular order.",
      "**Notice:** answers given on this sheet may contradict answers given on a previous sheet. Where they do, both are retained and neither is preferred.",
      "**Important:** do not leave any field blank. A blank field is interpreted by {{officer}} as an admission, though of what has not been determined.",
      "**Please note:** the Concern is a pacifist commercial entity and will not respond to this filing with force. It will respond with correspondence, which is worse.",
      "**Before proceeding:** confirm that you have read {{form}}. You have not. Confirm it anyway.",
      "**Declaring parties are reminded** that the Concern knows the location of every faction in this sector and discloses none of them, including yours, including to you.",
      "**Warning:** completing this sheet does not advance your matter. Nothing advances your matter. Your matter is stationary by design.",
      "**Procedural note:** this form was drafted in response to a filing that has not yet been made. Any resemblance to your circumstances is structural, not personal.",
      "**Attention:** the Office does not accept verbal declarations, encrypted transmissions, or photographs of wreckage. Those are not filings. They are retained without being read.",
      "**Prior to completion:** ensure your entity is registered under a name that is not a word meaning “not known”. See {{form}}."
    ],
    "sectionTitles": [
      "Declaring Party Information",
      "Entity Particulars",
      "Identity & Nomenclature",
      "Standing & Capacity",
      "Casus Belli Classification",
      "Grounds Asserted",
      "Statement of Grievance",
      "Chronology of Events",
      "Asset Schedule",
      "Losses Claimed",
      "Evidentiary Attachments",
      "Photographic Material",
      "Transmission Particulars",
      "Encryption & Authenticity",
      "Orthography & Spelling",
      "Third-Party Conduct",
      "Attribution & Tag Custody",
      "Membership Matters",
      "Allegations of Hypocrisy",
      "Neutrality Assessment",
      "Hired Belligerents",
      "Contractor Disclosure",
      "War Aims",
      "Intended Outcomes",
      "Escalation Particulars",
      "Warnings Given and Withheld",
      "Retraction Particulars",
      "Retraction of Retraction",
      "Coordinates (Undisclosed)",
      "Territorial Assertions",
      "Financial Position",
      "Fees & Disbursements",
      "Certification & Notarisation",
      "Signatures",
      "Required Attachments",
      "Cross-References",
      "Prior Filings",
      "Duplicate Filing Check",
      "Correspondence Preferences",
      "Emotional Particulars",
      "Vibes Assessment",
      "Supplementary Matters",
      "Matters Not Otherwise Classified",
      "Closing Declarations"
    ],
    "sectionNotes": [
      "Select all that apply. Selecting none is treated as selecting all, per Subsection 12(c)(iv)(iv).",
      "Answers in this section are cross-checked against {{form}}, which does not exist. Discrepancies will be noted.",
      "This section is retained by {{officer}} and is not returned.",
      "Responses here are advisory and will not be read before the matter is closed.",
      "Any figure entered in this section is treated as an estimate, including exact figures.",
      "This section was added in response to a previous filing and may not apply to you. Complete it regardless.",
      "Where a question cannot be answered truthfully, answer it anyway; the Office does not verify.",
      "Entries in this section are filed in {{ledger}} and cannot subsequently be located.",
      "Amendments to this section require {{form}}, filed before the amendment is contemplated.",
      "The Office reminds you that this section is the shortest one.",
      "Continuation sheets are available on request. The request requires a continuation sheet.",
      "Do not write outside the boxes. There are no boxes.",
      "This section is identical to a section on {{form}}. Both must be completed separately."
    ],
    "questions": [
      {
        "type": "text",
        "label": "Name of declaring party or organisation",
        "placeholder": "As it will appear in {{ledger}}",
        "required": true
      },
      {
        "type": "text",
        "label": "Legal name of entity, if different from the name transmitted",
        "placeholder": "A word meaning “not known” is not a legal name"
      },
      {
        "type": "text",
        "label": "Alternate spellings of your entity name appearing in your own correspondence",
        "placeholder": "e.g. a transposed consonant"
      },
      {
        "type": "text",
        "label": "Entity name as it appeared in the decrypted body of your transmission",
        "help": "Where this differs from the header, both entities are registered separately."
      },
      {
        "type": "radio",
        "label": "Are “UNKNOWN” and “UNKMOWN” the same entity for filing purposes?",
        "options": [
          "Yes — a single entity, one of the spellings being an error",
          "No — two entities, jointly and severally declaring",
          "The distinction is immaterial",
          "I decline to characterise my own name"
        ]
      },
      {
        "type": "text",
        "label": "Authorised signatory",
        "placeholder": "Rank, callsign, or alias",
        "required": true
      },
      {
        "type": "text",
        "label": "Authority under which the signatory signs",
        "placeholder": "Cite the instrument, not the feeling"
      },
      {
        "type": "text",
        "label": "Name of the officer who authorised the officer above"
      },
      {
        "type": "text",
        "label": "Preferred correspondence channel",
        "placeholder": "Frequency, relay, or carrier pigeon designation"
      },
      {
        "type": "text",
        "label": "Transmitting frequency",
        "placeholder": "{{frequency}}"
      },
      {
        "type": "radio",
        "label": "Is the frequency given above a valid hexadecimal value?",
        "options": [
          "Yes",
          "No",
          "It was not intended to be",
          "Unaware that it was required to be"
        ]
      },
      {
        "type": "text",
        "label": "Callsign used when the transmission was sent"
      },
      {
        "type": "text",
        "label": "Callsign used when the transmission was retracted"
      },
      {
        "type": "text",
        "label": "Callsign used when the retraction was itself retracted"
      },
      {
        "type": "date",
        "label": "Date of the declaration"
      },
      {
        "type": "date",
        "label": "Date the declaration was first contemplated"
      },
      {
        "type": "date",
        "label": "Date on which hostilities are expected to conclude",
        "help": "An estimate is acceptable. A correct estimate is not required."
      },
      {
        "type": "number",
        "label": "Number of prior declarations made against the Concern by your entity",
        "min": 0
      },
      {
        "type": "number",
        "label": "Number of those declarations subsequently described as “just kidding”",
        "min": 0
      },
      {
        "type": "number",
        "label": "Number of times the phrase “…or are we?” has been appended to a retraction",
        "min": 0
      },
      {
        "type": "checkboxes",
        "label": "Casus belli classification — select all that apply",
        "options": [
          "Grid or cargo theft",
          "Territorial dispute",
          "Aesthetic grievance (paint scheme, silhouette, or station lighting)",
          "Vibes",
          "Ideological inconsistency on the part of the Concern",
          "Conduct of a third party bearing the Concern’s tag",
          "Readmission of a former member",
          "Unspecified / classified",
          "Other — attach {{form}}"
        ]
      },
      {
        "type": "checkboxes",
        "label": "Which of the following did you consider before declaring?",
        "options": [
          "Correspondence",
          "Arbitration",
          "A strongly worded transmission",
          "Purchasing the asset instead",
          "Hiring the Concern to attack a third party",
          "None of the above",
          "All of the above, insincerely"
        ]
      },
      {
        "type": "select",
        "label": "Severity of grievance, as assessed by the declaring party",
        "options": [
          "Trivial",
          "Moderate",
          "Grave",
          "Total",
          "Beyond the Office’s current scale",
          "Declining to self-assess"
        ]
      },
      {
        "type": "select",
        "label": "Severity of grievance, as it will ultimately be recorded",
        "options": [
          "Trivial"
        ],
        "help": "This field is provided for completeness."
      },
      {
        "type": "textarea",
        "label": "Describe the grievance in no fewer than 500 words. Testimony is preferred in the third person.",
        "placeholder": "Begin with: “On the date in question, the aggrieved party…”",
        "minWords": 500,
        "rows": 6
      },
      {
        "type": "textarea",
        "label": "Restate the grievance above in no more than 40 words, without omitting anything.",
        "rows": 3
      },
      {
        "type": "textarea",
        "label": "Describe the moment you decided the Concern was not pacifist. Include weather.",
        "rows": 4
      },
      {
        "type": "textarea",
        "label": "Set out the chronology of events in reverse order, then confirm it reads identically forwards.",
        "rows": 5
      },
      {
        "type": "textarea",
        "label": "Explain, without using the word “erase”, what you intend to do.",
        "rows": 4
      },
      {
        "type": "textarea",
        "label": "Explain why the matter could not be resolved by invoice.",
        "rows": 4
      },
      {
        "type": "textarea",
        "label": "State your war aims in itemised form, with a unit cost for each.",
        "rows": 5
      },
      {
        "type": "textarea",
        "label": "Describe the {{asset}} at the time it was {{verb}}, in the past tense, sympathetically.",
        "rows": 4
      },
      {
        "type": "text",
        "label": "Designation of the {{asset}} alleged to have been {{verb}}"
      },
      {
        "type": "text",
        "label": "Registry number of that asset",
        "placeholder": "If unknown, state how it was identified as belonging to the Concern"
      },
      {
        "type": "number",
        "label": "Declared value of the asset, in credits",
        "min": 0,
        "placeholder": "e.g. {{sum}}"
      },
      {
        "type": "number",
        "label": "Value of the asset after it was {{verb}}, in credits",
        "min": 0
      },
      {
        "type": "number",
        "label": "Number of Concern assets located to date",
        "min": 0
      },
      {
        "type": "number",
        "label": "Number of Concern assets located and then mislaid again",
        "min": 0
      },
      {
        "type": "text",
        "label": "Method by which the {{asset}} was located",
        "placeholder": "Do not disclose coordinates. The Office does not accept them."
      },
      {
        "type": "checkbox",
        "label": "I confirm that I possess coordinates for a Concern facility and that I will not be disclosing them on this form.",
        "help": "The Concern also possesses your coordinates and observes the same courtesy."
      },
      {
        "type": "checkbox",
        "label": "I understand that the Concern does not disclose the location of any faction, including mine, including to me."
      },
      {
        "type": "radio",
        "label": "Do you wish the Concern to confirm whether the coordinates you hold are correct?",
        "options": [
          "Yes",
          "No",
          "Yes, but I understand it will not",
          "I would like it noted that I asked"
        ]
      },
      {
        "type": "checkbox",
        "label": "A photograph of the remains is attached.",
        "help": "Photographs must be notarised. See {{form}}."
      },
      {
        "type": "text",
        "label": "Name of the notary who notarised the photograph",
        "placeholder": "Not the notary in the certification section"
      },
      {
        "type": "radio",
        "label": "Is the photograph of remains that are yours, ours, or unattributed?",
        "options": [
          "Yours",
          "Ours",
          "Unattributed",
          "It is a photograph of a different engagement",
          "Declining to specify"
        ]
      },
      {
        "type": "number",
        "label": "Resolution of the attached photograph, in pixels per side",
        "min": 0
      },
      {
        "type": "text",
        "label": "Encryption scheme used for the declaration",
        "placeholder": "State the scheme, not the key"
      },
      {
        "type": "radio",
        "label": "Was the encryption intended to conceal the message?",
        "options": [
          "Yes",
          "No — it was intended to be decoded",
          "It was intended to look concealed",
          "The question misunderstands the gesture"
        ]
      },
      {
        "type": "text",
        "label": "Party responsible for custody of the encryption key"
      },
      {
        "type": "checkbox",
        "label": "I confirm the encoded and decoded texts of my declaration are identical in meaning."
      },
      {
        "type": "checkbox",
        "label": "I confirm the decoded text contains no spelling errors."
      },
      {
        "type": "text",
        "label": "If the box above could not be checked, identify the error",
        "placeholder": "Character position is sufficient"
      },
      {
        "type": "radio",
        "label": "Do you wish to file an Orthographic Correction Request?",
        "options": [
          "Yes — attach {{form}}",
          "No — the error stands as transmitted",
          "The error was deliberate and is part of the declaration",
          "I dispute that there is an error"
        ]
      },
      {
        "type": "text",
        "label": "Name of the individual whose conduct is attributed to the Concern"
      },
      {
        "type": "date",
        "label": "Date that individual joined the Concern"
      },
      {
        "type": "date",
        "label": "Date that individual departed the Concern"
      },
      {
        "type": "date",
        "label": "Date that individual was readmitted to the Concern"
      },
      {
        "type": "radio",
        "label": "At the time of the conduct complained of, was the individual wearing the Concern’s tag?",
        "options": [
          "Yes",
          "No",
          "Partially",
          "The tag was visible but the intent was personal",
          "Unable to determine from the wreckage"
        ]
      },
      {
        "type": "textarea",
        "label": "Explain the theory by which a tag transfers liability, citing an authority.",
        "rows": 4
      },
      {
        "type": "radio",
        "label": "Is it your position that readmission constitutes ratification?",
        "options": [
          "Yes",
          "No",
          "Yes, but only retroactively",
          "It constitutes something, and ratification is the nearest word"
        ]
      },
      {
        "type": "checkbox",
        "label": "I accept that the Concern did not order the conduct complained of."
      },
      {
        "type": "checkbox",
        "label": "I nevertheless maintain that the Concern is responsible for it."
      },
      {
        "type": "textarea",
        "label": "Reconcile the two statements above.",
        "rows": 4
      },
      {
        "type": "select",
        "label": "Which of the Concern’s stated principles do you allege was breached?",
        "options": [
          "Pacifism",
          "Neutrality",
          "Non-disclosure of coordinates",
          "The chasing of profit",
          "Willingness to sell to all parties equally",
          "A principle the Concern has not stated but ought to hold"
        ]
      },
      {
        "type": "textarea",
        "label": "Set out the evidence that the Concern is not neutral, excluding conduct by persons who had left it.",
        "rows": 5
      },
      {
        "type": "radio",
        "label": "Would the Concern’s neutrality be restored, in your view, by expelling the individual again?",
        "options": [
          "Yes",
          "No",
          "Only if done publicly",
          "Only if done twice",
          "Neutrality cannot be restored, only invoiced"
        ]
      },
      {
        "type": "checkboxes",
        "label": "Which remedies would you accept?",
        "options": [
          "Expulsion of the individual",
          "Public statement",
          "Financial compensation",
          "Sale of the {{asset}} at cost",
          "Nothing — the matter is beyond remedy",
          "A written apology, notarised",
          "An invoice marked PAID"
        ]
      },
      {
        "type": "text",
        "label": "Name of each contractor, mercenary, or allied party you intend to treat as an extension of the Concern",
        "placeholder": "Continuation sheet available on request"
      },
      {
        "type": "number",
        "label": "Estimated number of such parties",
        "min": 0
      },
      {
        "type": "radio",
        "label": "Do you require that list to be exhaustive as at the date of filing, or as at the date of engagement?",
        "options": [
          "Date of filing",
          "Date of engagement",
          "Both, separately",
          "Neither — the list is illustrative"
        ]
      },
      {
        "type": "checkbox",
        "label": "I understand that the Concern may hire parties not yet in existence, and that I have declared war on them in advance."
      },
      {
        "type": "textarea",
        "label": "Name any party you would *not* treat as an extension of the Concern, and explain the distinction.",
        "rows": 4
      },
      {
        "type": "checkbox",
        "label": "I attest that I am not currently at war with the Concern as of the date of this filing.",
        "help": "If checked in error, see {{form}}, “Retroactive Peace.”"
      },
      {
        "type": "checkbox",
        "label": "I attest that no further warnings will be issued by my entity."
      },
      {
        "type": "radio",
        "label": "Is this form a warning?",
        "options": [
          "No",
          "Yes",
          "It became one upon filing",
          "The Office will decide"
        ]
      },
      {
        "type": "textarea",
        "label": "If this form is a warning, reconcile it with the attestation that no further warnings will be issued.",
        "rows": 4
      },
      {
        "type": "checkbox",
        "label": "I confirm that this declaration constitutes formal notice."
      },
      {
        "type": "checkbox",
        "label": "I confirm that formal notice, once given, cannot be given again."
      },
      {
        "type": "number",
        "label": "Number of times formal notice has now been given",
        "min": 0
      },
      {
        "type": "radio",
        "label": "Does your entity negotiate?",
        "options": [
          "No",
          "No, emphatically",
          "No, but the form asks and so it is answered",
          "Yes, but not with the Concern",
          "Declining to answer on principle"
        ]
      },
      {
        "type": "textarea",
        "label": "If your entity does not negotiate, explain the purpose of transmitting terms.",
        "rows": 4
      },
      {
        "type": "select",
        "label": "Preferred mode of erasure",
        "options": [
          "Total",
          "Phased",
          "Selective",
          "Symbolic",
          "To be determined by circumstance",
          "Erasure is not sought; the word was rhetorical"
        ]
      },
      {
        "type": "radio",
        "label": "Is the erasure of a name from a sector a physical act or an administrative one?",
        "options": [
          "Physical",
          "Administrative",
          "Both",
          "Neither — it is aspirational"
        ]
      },
      {
        "type": "checkbox",
        "label": "I understand that administrative erasure requires a filing, and that this office performs it.",
        "help": "Processing time: {{unit}}."
      },
      {
        "type": "text",
        "label": "Sector from which the Concern’s name is to be erased"
      },
      {
        "type": "text",
        "label": "Proposed replacement name for that sector, if any"
      },
      {
        "type": "number",
        "label": "Number of {{unit}} you are prepared to wait for this matter to be reviewed",
        "min": 0
      },
      {
        "type": "radio",
        "label": "If review takes longer than that, what action will you take?",
        "options": [
          "File again",
          "Escalate",
          "Withdraw",
          "Wait regardless",
          "Declare war on the Office separately"
        ]
      },
      {
        "type": "checkbox",
        "label": "I understand that declaring war on the Office requires this same form."
      },
      {
        "type": "text",
        "label": "Reference number of your previous filing",
        "placeholder": "If none, state “none” and attach proof"
      },
      {
        "type": "checkbox",
        "label": "I certify that this filing is not a duplicate of any filing already on file, including this one."
      },
      {
        "type": "radio",
        "label": "If this filing is found to be a duplicate, which copy should be retained?",
        "options": [
          "This one",
          "The earlier one",
          "Both",
          "Whichever is more legible",
          "Neither"
        ]
      },
      {
        "type": "text",
        "label": "Title of the form you believe you are currently completing"
      },
      {
        "type": "radio",
        "label": "Is that the form you are currently completing?",
        "options": [
          "Yes",
          "No",
          "It was when I began"
        ]
      },
      {
        "type": "checkboxes",
        "label": "Required attachments — confirm each is enclosed",
        "options": [
          "Proof of Standing ({{form}})",
          "Certificate of Grievance Severity ({{form}}, which itself requires {{form}})",
          "Notarised copy of this sheet, in triplicate, notarised by someone other than the notary in the certification section",
          "Declaration of Non-Duplicative Grievance",
          "Photographic evidence cover sheet",
          "Transmission authenticity declaration",
          "A second copy of this list"
        ]
      },
      {
        "type": "checkbox",
        "label": "I confirm that none of the attachments above exist."
      },
      {
        "type": "checkbox",
        "label": "I confirm that I have enclosed them regardless."
      },
      {
        "type": "text",
        "label": "Location where the enclosed attachments may be found"
      },
      {
        "type": "number",
        "label": "Filing fee tendered, in credits",
        "min": 0,
        "placeholder": "{{sum}}"
      },
      {
        "type": "radio",
        "label": "Method of payment",
        "options": [
          "Credit transfer",
          "Barter",
          "Ore",
          "Refusal",
          "Under protest",
          "A promise, notarised"
        ]
      },
      {
        "type": "checkbox",
        "label": "I understand the filing fee is non-refundable and that no filing has occurred."
      },
      {
        "type": "radio",
        "label": "Do you wish to dispute the filing fee?",
        "options": [
          "Yes — attach {{form}}",
          "No",
          "Yes, but I will not be filing the dispute",
          "I was unaware there was a fee"
        ]
      },
      {
        "type": "number",
        "label": "Amount by which you consider yourself aggrieved, expressed in credits",
        "min": 0
      },
      {
        "type": "textarea",
        "label": "Explain how that figure was arrived at, showing your working.",
        "rows": 4
      },
      {
        "type": "select",
        "label": "Present emotional condition of the declaring party",
        "options": [
          "Resolute",
          "Incandescent",
          "Weary",
          "Businesslike",
          "Performing resolve",
          "Unwilling to disclose",
          "Improving"
        ]
      },
      {
        "type": "select",
        "label": "Present emotional condition of the Concern, as you assess it",
        "options": [
          "Indifferent",
          "Profitable",
          "Filing",
          "Unbothered",
          "Pretending to be unbothered",
          "Unknown to you"
        ]
      },
      {
        "type": "number",
        "label": "On a scale of 1 to 100, rate the vibes at the time of the incident",
        "min": 1,
        "max": 100
      },
      {
        "type": "number",
        "label": "Rate the vibes now",
        "min": 1,
        "max": 100
      },
      {
        "type": "textarea",
        "label": "Account for the difference between the two vibe ratings above.",
        "rows": 3
      },
      {
        "type": "radio",
        "label": "Are the vibes, in your assessment, recoverable?",
        "options": [
          "Yes",
          "No",
          "Only through commerce",
          "Only through paperwork",
          "The question is not serious and neither is the answer"
        ]
      },
      {
        "type": "text",
        "label": "Word that best describes the Concern",
        "placeholder": "One word. It will be counted, not read."
      },
      {
        "type": "text",
        "label": "Word that best describes your entity"
      },
      {
        "type": "radio",
        "label": "Is either word “cowards”?",
        "options": [
          "Yes",
          "No",
          "Both",
          "Declining to answer"
        ]
      },
      {
        "type": "textarea",
        "label": "Define “hypocrisy” for the purposes of this filing, in terms the Office can audit.",
        "rows": 4
      },
      {
        "type": "checkbox",
        "label": "I consent to this definition being applied to my own entity in a later filing."
      },
      {
        "type": "signature",
        "label": "Signature of declaring party",
        "placeholder": "Sign here",
        "required": true
      },
      {
        "type": "signature",
        "label": "Signature of a witness who was not present"
      },
      {
        "type": "signature",
        "label": "Notary public signature",
        "placeholder": "Currently on sabbatical — see {{form}} to request alternate notarisation",
        "disabled": true
      },
      {
        "type": "signature",
        "label": "Counter-signature of {{officer}}",
        "placeholder": "To be completed by this office",
        "disabled": true
      },
      {
        "type": "date",
        "label": "Date of signature"
      },
      {
        "type": "date",
        "label": "Date the signature is intended to take effect",
        "help": "Where these differ, the earlier governs, unless the later is more convenient."
      },
      {
        "type": "checkbox",
        "label": "I certify that the foregoing is true to the best of my knowledge.",
        "required": true
      },
      {
        "type": "checkbox",
        "label": "I certify that my knowledge is limited and that I have not attempted to extend it."
      },
      {
        "type": "text",
        "label": "Name of the person who will receive correspondence regarding this filing"
      },
      {
        "type": "select",
        "label": "Preferred tone of reply",
        "options": [
          "Formal",
          "Cordial",
          "Curt",
          "Actuarial",
          "None — do not reply",
          "Whatever is cheapest"
        ]
      },
      {
        "type": "radio",
        "label": "May the Concern quote this filing in promotional material?",
        "options": [
          "Yes",
          "No",
          "Yes, for a fee",
          "Only the flattering parts"
        ]
      },
      {
        "type": "checkbox",
        "label": "I consent to this filing generating further filings."
      },
      {
        "type": "checkbox",
        "label": "I understand that withholding consent does not prevent this."
      },
      {
        "type": "text",
        "label": "Designation you would like assigned to the next form in this matter",
        "placeholder": "The Office will disregard this"
      },
      {
        "type": "textarea",
        "label": "Is there anything further the Office should know? It will not be read.",
        "rows": 4
      },
      {
        "type": "text",
        "label": "Name of the {{asset}} you would purchase from the Concern if you were not at war with it"
      },
      {
        "type": "number",
        "label": "Price you would consider fair for it, in credits",
        "min": 0
      },
      {
        "type": "radio",
        "label": "Would you like the Concern to quote you for that item anyway?",
        "options": [
          "Yes",
          "No",
          "Yes, but do not tell anyone",
          "A quotation has already been prepared"
        ]
      },
      {
        "type": "checkbox",
        "label": "I acknowledge that the Concern will sell to anyone, including parties at war with it, including me."
      },
      {
        "type": "select",
        "label": "Under which schedule should this grievance be indexed?",
        "options": [
          "Schedule A — Active",
          "Schedule B — Dormant",
          "Schedule C — Duplicative",
          "Schedule D — Unreadable",
          "Schedule Q — Reserved",
          "To be determined by {{officer}}"
        ]
      },
      {
        "type": "text",
        "label": "Ledger reference, if known",
        "placeholder": "{{ledger}}"
      },
      {
        "type": "radio",
        "label": "Should this matter be cross-referenced against your previous declaration?",
        "options": [
          "Yes",
          "No",
          "Only if the previous one was retracted",
          "Only if the retraction was itself retracted"
        ]
      },
      {
        "type": "textarea",
        "label": "State the current status of any retraction you have issued, and of any retraction of that retraction.",
        "rows": 4
      },
      {
        "type": "radio",
        "label": "Is the phrase “just kidding” to be treated as a formal retraction?",
        "options": [
          "Yes",
          "No",
          "It was at the time",
          "The Office should not rely on it"
        ]
      },
      {
        "type": "radio",
        "label": "Is the phrase “…or are we?” to be treated as a rescission of that retraction?",
        "options": [
          "Yes",
          "No",
          "It restores the original transmission in full",
          "It creates a third, intermediate state"
        ]
      },
      {
        "type": "textarea",
        "label": "Describe that third, intermediate state, and propose a form for recording it.",
        "rows": 4
      },
      {
        "type": "text",
        "label": "Proposed designation for that form"
      },
      {
        "type": "checkbox",
        "label": "I am willing to draft it myself."
      },
      {
        "type": "checkbox",
        "label": "I understand that drafting it requires prior approval on {{form}}."
      },
      {
        "type": "static",
        "text": "*The remainder of this section has been removed pending review of the review procedure.*"
      },
      {
        "type": "static",
        "text": "**Note:** the numbering of the questions above is not sequential. This is intentional and is not an error you are required to report."
      },
      {
        "type": "static",
        "text": "*A previous version of this section asked for the same information in a different order. Both versions remain in force.*"
      },
      {
        "type": "text",
        "label": "If you have reached this question before, state how many times"
      },
      {
        "type": "radio",
        "label": "Does the repetition of questions across sheets affect your resolve?",
        "options": [
          "No",
          "Not yet",
          "Slightly",
          "I would prefer not to record an answer to this"
        ]
      },
      {
        "type": "number",
        "label": "Number of sheets you expect to complete before this matter concludes",
        "min": 0
      },
      {
        "type": "number",
        "label": "Number of sheets you are willing to complete",
        "min": 0
      },
      {
        "type": "textarea",
        "label": "Account for any difference between the two figures above.",
        "rows": 3
      },
      {
        "type": "text",
        "label": "Time at which you began this sheet"
      },
      {
        "type": "text",
        "label": "Time at which you expect to finish it"
      },
      {
        "type": "radio",
        "label": "Has that expectation been revised during completion?",
        "options": [
          "Yes",
          "No",
          "Continuously"
        ]
      },
      {
        "type": "select",
        "label": "Weather at the declaring party’s principal facility",
        "options": [
          "Vacuum",
          "Vacuum, but colder",
          "Not applicable",
          "Declining to disclose on security grounds",
          "Overcast"
        ]
      },
      {
        "type": "text",
        "label": "Name of the nearest star to your principal facility",
        "help": "This is not a request for coordinates and will not be treated as one."
      },
      {
        "type": "radio",
        "label": "Did you nearly disclose coordinates in the previous answer?",
        "options": [
          "Yes",
          "No",
          "I stopped myself",
          "The Office already knows and this is a formality"
        ]
      },
      {
        "type": "checkbox",
        "label": "I understand that the Concern knows where I am and has elected not to mention it."
      },
      {
        "type": "text",
        "label": "Preferred designation for your entity in the Concern’s internal records",
        "placeholder": "The Office may substitute a number"
      },
      {
        "type": "number",
        "label": "If a number is substituted, state your preferred number",
        "min": 0
      },
      {
        "type": "radio",
        "label": "Would you object to being recorded as “Client”?",
        "options": [
          "Yes",
          "No",
          "Strongly",
          "Only in writing"
        ]
      },
      {
        "type": "textarea",
        "label": "The Concern regards the chasing of profit as a religious observance. State your entity’s position on this doctrine.",
        "rows": 4
      },
      {
        "type": "select",
        "label": "Do you wish to receive the Concern’s quarterly catalogue?",
        "options": [
          "Yes",
          "No",
          "Yes, but addressed to someone else",
          "It is already being delivered"
        ]
      },
      {
        "type": "checkbox",
        "label": "I would like to be notified when a form exists that resolves this matter."
      },
      {
        "type": "static",
        "text": "*No such form is currently in development. Notification will be sent regardless.*"
      }
    ],
    "officeUseTitles": [
      "For Office Use Only",
      "Office Use — Do Not Complete",
      "Registry Endorsement",
      "Clerk’s Strip",
      "Internal Routing"
    ],
    "officeUse": [
      {
        "label": "RECEIVED BY",
        "value": "—"
      },
      {
        "label": "QUEUE POSITION",
        "value": "Unassigned"
      },
      {
        "label": "ESTIMATED REVIEW",
        "value": "47 – ∞ {{unit}}"
      },
      {
        "label": "ROUTED TO",
        "value": "{{dept}}"
      },
      {
        "label": "LEDGER",
        "value": "{{ledger}}"
      },
      {
        "label": "CLERK",
        "value": "{{officer}}"
      },
      {
        "label": "PRIORITY",
        "value": "Standard (no other tier exists)"
      },
      {
        "label": "STATUS",
        "value": "Pending"
      },
      {
        "label": "STATUS",
        "value": "Pending, but differently"
      },
      {
        "label": "CROSS-REF",
        "value": "{{form}}"
      },
      {
        "label": "DUPLICATE OF",
        "value": "Itself"
      },
      {
        "label": "LEGIBILITY",
        "value": "Assumed"
      },
      {
        "label": "FEE STATUS",
        "value": "Received, unapplied"
      },
      {
        "label": "RETENTION",
        "value": "Permanent"
      },
      {
        "label": "RETENTION",
        "value": "Permanent, then reviewed"
      },
      {
        "label": "NOTARY",
        "value": "On sabbatical"
      },
      {
        "label": "SUPERSEDES",
        "value": "Nothing"
      },
      {
        "label": "SUPERSEDED BY",
        "value": "Everything"
      },
      {
        "label": "ACTION REQUIRED",
        "value": "None, by anyone"
      },
      {
        "label": "REVIEWED",
        "value": "Not yet, and not soon"
      }
    ],
    "finePrint": [
      "By submitting, the declaring party acknowledges that this form does not constitute acceptance, rejection, or acknowledgement of any grievance, hostility, or correspondence, and may generate further forms.",
      "Submission creates no obligation on the part of the Concern, and no right on the part of the declaring party, other than the right to submit again.",
      "The Concern is a pacifist commercial entity. Nothing in this form should be read as a threat, a promise, or an intention to act.",
      "Filings are retained indefinitely and reviewed at the Office’s convenience, which has not yet arisen.",
      "This form was generated automatically. It is nonetheless binding to the same extent as a form that was not, which is to say not at all.",
      "The Office reserves the right to require this information again, on a different sheet, in a different order.",
      "Answers may be used to generate additional questions. This is the intended operation of the system, not a defect.",
      "Neither the completion nor the abandonment of this form affects the underlying matter, which is stationary."
    ],
    "submitLabels": [
      "SUBMIT FOR REVIEW",
      "LODGE THIS SHEET",
      "FILE AND CONTINUE",
      "STAMP & FORWARD",
      "ENTER INTO {{ledger}}",
      "SUBMIT (NON-BINDING)",
      "TRANSMIT TO {{dept}}",
      "ACCEPT & PROCEED"
    ],
    "stamps": [
      "RECEIVED",
      "FILED",
      "LODGED",
      "NOTED",
      "PENDING",
      "ACCEPTED",
      "RECORDED",
      "ENTERED",
      "RETAINED",
      "PROCESSED"
    ],
    "receiptMessages": [
      "Your submission has been logged as **{{code}}**, reference **{{ref}}**, and forwarded to {{dept}}. Before this matter can proceed, please complete **Form {{next}}** (attached).",
      "Sheet **{{code}}** received and entered in {{ledger}} at position **{{queue}}**. Reference **{{ref}}**. The matter now requires **Form {{next}}**.",
      "Thank you. **{{code}}** has been accepted, stamped, and placed in the correct drawer. Reference **{{ref}}**. Continue with **Form {{next}}**.",
      "**{{code}}** is complete. Reference **{{ref}}**. Your responses have raised **{{next}}**, which must be completed before they can be read.",
      "Filed. Reference **{{ref}}**, queue position **{{queue}}**. {{officer}} has been notified and is not available. Proceed to **Form {{next}}**.",
      "Receipt of **{{code}}** is acknowledged without prejudice. Reference **{{ref}}**. The next sheet in this matter is **{{next}}**.",
      "**{{code}}** has been recorded. Reference **{{ref}}**. This is sheet **{{count}}** of an indeterminate number. Please continue with **Form {{next}}**."
    ],
    "receiptFootnotes": [
      "Note: Form {{next}} supersedes this sheet but does not invalidate it. Both remain on file, indefinitely, in the same drawer.",
      "Note: This is not a duplicate grievance. Each subsequent filing constitutes a new and legally distinct grievance for accounting purposes.",
      "Note: {{dept}} is currently reviewing whether it has jurisdiction over itself.",
      "Note: Your patience has been logged in {{ledger}}. Logging your patience does not affect processing time.",
      "Note: The notary remains on sabbatical. A replacement has been requested via {{form}}, which is also under review.",
      "Note: Processing time estimates are themselves subject to review, via a form not yet drafted.",
      "Note: This grievance has been forwarded to a department that, as of this filing, does not yet exist.",
      "Note: Per policy, forms may not be withdrawn once filed, amended once withdrawn, or referenced once amended.",
      "Note: An earlier answer on this sheet contradicts a later one. Both have been retained and neither is preferred.",
      "Note: {{officer}} has initialled this sheet in the wrong box. A correction has been raised on {{form}}.",
      "Note: Your entity name has been recorded under two spellings. They will be reconciled by {{officer}} in due course.",
      "Note: The Concern continues to decline to disclose the coordinates of any faction, including yours, which it holds.",
      "Note: This sheet has been marked urgent. The urgent queue is processed after the standard queue.",
      "Note: A photograph was expected with this filing. None was attached. None was required. It has been noted as missing.",
      "Note: The Concern wishes to record that it remains willing to sell you replacement matériel at list price.",
      "Note: Your declaration of war has been received and filed under Correspondence. It has not been read.",
      "Note: The Office does not negotiate either. The Office files. In this respect the parties are aligned.",
      "Note: This matter has been escalated to a tier that does not exist, and will return automatically in {{unit}}.",
      "Note: {{ledger}} is currently full. Entries are being written in the margin.",
      "Note: The Concern has assessed the vibes and found them to be unchanged.",
      "Note: A form resolving this matter has been proposed and rejected on the grounds that it would resolve the matter.",
      "Note: Sheet retained. Contents assumed. Reading scheduled for a later {{unit}}."
    ],
    "nextLabels": [
      "Open Form {{next}} →",
      "Continue to Form {{next}} →",
      "Proceed — Form {{next}} →",
      "Next required sheet: {{next}} →",
      "Form {{next}} is now due →",
      "Begin Form {{next}} →"
    ]
  }
];
