#!/usr/bin/env node
/* ============================================================
   build.mjs

   1. Bundles /forms/*.json into a module the functions import,
      so no filesystem access is needed at request time.
   2. Copies the admin shell to the secret path named by
      ADMIN_PATH, so the page only exists at that URL.
   ============================================================ */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FORMS_DIR = path.join(root, 'forms');
const PUBLIC_DIR = path.join(root, 'public');
const SEED_OUT = path.join(root, 'netlify', 'functions', 'lib', 'seed-forms.mjs');
const MANIFEST = path.join(PUBLIC_DIR, '.generated.json');

const DEFAULT_ADMIN_PATH = 'ledger-7';

function log(msg) { process.stdout.write('  ' + msg + '\n'); }
function warn(msg) { process.stdout.write('  ! ' + msg + '\n'); }

/* ---------- 1. seed documents ---------- */

async function bundleSeeds() {
  let names = [];
  try {
    names = (await fs.readdir(FORMS_DIR)).filter((n) => n.endsWith('.json'));
  } catch {
    warn('No /forms directory; the site will start with no seed forms.');
  }

  const forms = [];
  const banks = [];

  for (const name of names.sort()) {
    const raw = await fs.readFile(path.join(FORMS_DIR, name), 'utf8');
    let doc;
    try {
      doc = JSON.parse(raw);
    } catch (err) {
      throw new Error('forms/' + name + ' is not valid JSON: ' + err.message);
    }
    if (doc.kind === 'bank') banks.push(doc);
    else forms.push(doc);
  }

  const body =
    '/* GENERATED by scripts/build.mjs - do not edit.\n' +
    '   Source of truth is /forms/*.json. */\n\n' +
    'export const SEED_FORMS = ' + JSON.stringify(forms, null, 2) + ';\n\n' +
    'export const SEED_BANKS = ' + JSON.stringify(banks, null, 2) + ';\n';

  await fs.mkdir(path.dirname(SEED_OUT), { recursive: true });
  await fs.writeFile(SEED_OUT, body, 'utf8');

  const questions = banks.reduce((n, b) => n + (b.questions || []).length, 0);
  log('Bundled ' + forms.length + ' form(s) and ' + banks.length + ' bank(s), ' +
      questions + ' questions total.');
}

/* ---------- 2. admin shell at the secret path ---------- */

function sanitizePath(p) {
  const clean = String(p || '').trim().replace(/^\/+|\/+$/g, '');
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(clean)) return null;
  return clean;
}

async function placeAdminShell() {
  const requested = process.env.ADMIN_PATH || DEFAULT_ADMIN_PATH;
  const adminPath = sanitizePath(requested);

  if (!adminPath) {
    throw new Error('ADMIN_PATH "' + requested + '" is not usable. Use letters, numbers, dots, hyphens ' +
      'and underscores only, with no slashes.');
  }
  if (adminPath === DEFAULT_ADMIN_PATH && !process.env.ADMIN_PATH) {
    warn('ADMIN_PATH is not set; using the default "/' + DEFAULT_ADMIN_PATH + '". Set your own before going live.');
  }

  // Remove the directory a previous build created, so the old secret
  // path stops working when it is changed.
  try {
    const prev = JSON.parse(await fs.readFile(MANIFEST, 'utf8'));
    if (prev.adminPath && prev.adminPath !== adminPath) {
      await fs.rm(path.join(PUBLIC_DIR, prev.adminPath), { recursive: true, force: true });
      log('Removed previous admin path /' + prev.adminPath);
    }
  } catch { /* no previous build */ }

  const shell = await fs.readFile(path.join(root, 'src', 'admin.html'), 'utf8');
  const dest = path.join(PUBLIC_DIR, adminPath);
  await fs.mkdir(dest, { recursive: true });
  await fs.writeFile(path.join(dest, 'index.html'), shell, 'utf8');
  await fs.writeFile(MANIFEST, JSON.stringify({ adminPath, builtAt: new Date().toISOString() }, null, 2), 'utf8');

  log('Admin page published at /' + adminPath);

  if (!process.env.ADMIN_PASSWORD) {
    warn('ADMIN_PASSWORD is not set. The admin page will refuse every login until it is.');
  } else if (process.env.ADMIN_PASSWORD.length < 12) {
    warn('ADMIN_PASSWORD is short. Use a long random string - this is the only lock on your submissions.');
  }
  if (!process.env.ADMIN_SECRET) {
    warn('ADMIN_SECRET is not set; session tokens are derived from the password, ' +
         'so changing the password will sign you out everywhere.');
  }
}

/* ---------- run ---------- */

process.stdout.write('\nCIC paperwork — build\n');
try {
  await bundleSeeds();
  await placeAdminShell();
  process.stdout.write('  Done.\n\n');
} catch (err) {
  process.stderr.write('\n  Build failed: ' + err.message + '\n\n');
  process.exit(1);
}
